package com.myehr.controller.webservice.cxf.erp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-04-18T17:00:27.294+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "CUX_OKC_BPMSERA_PKG_Service", 
                  wsdlLocation = "http://172.16.100.60:8002/webservices/SOAProvider/plsql/cux_okc_bpmsera_pkg/?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/apps/fnd/soaprovider/plsql/cux_okc_bpmsera_pkg/") 
public class CUXOKCBPMSERAPKGService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/apps/fnd/soaprovider/plsql/cux_okc_bpmsera_pkg/", "CUX_OKC_BPMSERA_PKG_Service");
    public final static QName CUXOKCBPMSERAPKGPort = new QName("http://xmlns.oracle.com/apps/fnd/soaprovider/plsql/cux_okc_bpmsera_pkg/", "CUX_OKC_BPMSERA_PKG_Port");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.100.60:8002/webservices/SOAProvider/plsql/cux_okc_bpmsera_pkg/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CUXOKCBPMSERAPKGService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.16.100.60:8002/webservices/SOAProvider/plsql/cux_okc_bpmsera_pkg/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CUXOKCBPMSERAPKGService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CUXOKCBPMSERAPKGService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CUXOKCBPMSERAPKGService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CUXOKCBPMSERAPKGService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CUXOKCBPMSERAPKGService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CUXOKCBPMSERAPKGService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CUXOKCBPMSERAPKGPortType
     */
    @WebEndpoint(name = "CUX_OKC_BPMSERA_PKG_Port")
    public CUXOKCBPMSERAPKGPortType getCUXOKCBPMSERAPKGPort() {
        return super.getPort(CUXOKCBPMSERAPKGPort, CUXOKCBPMSERAPKGPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CUXOKCBPMSERAPKGPortType
     */
    @WebEndpoint(name = "CUX_OKC_BPMSERA_PKG_Port")
    public CUXOKCBPMSERAPKGPortType getCUXOKCBPMSERAPKGPort(WebServiceFeature... features) {
        return super.getPort(CUXOKCBPMSERAPKGPort, CUXOKCBPMSERAPKGPortType.class, features);
    }

}
