package com.myehr.controller.webservice.cxf.erp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-04-18T17:00:27.274+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/apps/fnd/soaprovider/plsql/cux_okc_bpmsera_pkg/", name = "CUX_OKC_BPMSERA_PKG_PortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CUXOKCBPMSERAPKGPortType {

    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/fnd/soaprovider/plsql/cux_okc_bpmsera_pkg/bpmsera_main/", partName = "body")
    @WebMethod(operationName = "BPMSERA_MAIN", action = "http://ebs001.spichn.com.cn:8002/webservices/SOAProvider/plsql/cux_okc_bpmsera_pkg/")
    public OutputParameters bpmseraMAIN(
        @WebParam(partName = "header", name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/fnd/soaprovider/plsql/cux_okc_bpmsera_pkg/", header = true)
        SOAHeader header,
        @WebParam(partName = "body", name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/fnd/soaprovider/plsql/cux_okc_bpmsera_pkg/bpmsera_main/")
        InputParameters body
    );
}
